name:                h64
version:             0.1.0.0
github:              "TimeTravelPenguin/h64"
license:             GPL-3
author:              "Phillip Smith"
maintainer:          "Phillip Smith"
copyright:           "2022 Phillip Smith"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            A Mupen64 .m64 file parser
category:            File

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/TimeTravelPenguin/h64#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- text
- utf8-string
- strict
- lens
- binary

library:
  default-extensions:
    - OverloadedStrings
  source-dirs: src

executables:
  h64-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - h64

tests:
  h64-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - h64
    - QuickCheck
